### ISSUE TITLE
Pet Rat Icon Glitch Movement

### ISSUE THREAD

**Issue by Pie314** [MaxIsJoe/TWC#8]
Moving Left,Right,Down is fine. However, when going up, the Rat's icon keeps on glitching itself as shown. 
![twcmeow](https://user-images.githubusercontent.com/13006438/41382859-0237352e-6f3c-11e8-9179-b0706666b86e.PNG)

**Comment by MaxIsJoe** [comment]
Couple of questions : 

1. Do you have your client FPS set to something else other than the default?
2. Did this happen to you before or did this just happen?

**Comment by MaxIsJoe** [comment]
I checked out the problem, Dream seeker bugged out for you, it's not on the game's side, if you experience this again just clear you cache.
